sudo: required
services:
  - docker

before_install:
  - docker build -t khemgabz/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run khemgabz/react-test npm test -- --coverage --watchAll=false

after_success:
  - docker build -t khemgabz/multi-service-client ./client
  - docker build -t khemgabz/multi-service-nginx ./nginx
  - docker build -t khemgabz/multi-service-server ./server
  - docker build -t khemgabz/multi-service-worker ./worker
  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # take images and push to docker hub
  - docker push khemgabz/multi-service-client
  - docker push khemgabz/multi-service-nginx
  - docker push khemgabz/multi-service-server
  - docker push khemgabz/multi-service-worker
