sudo: required
services:
  - docker

before_install:
  - docker build -t khemgabz/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run khemgabz/react-test npm test -- --coverage --watchAll=false

after_success:
  - docker build -t khemgabz/multi-service-client ./client
  - docker build -t khemgabz/multi-service-nginx ./nginx
  - docker build -t khemgabz/multi-service-server ./server
  - docker build -t khemgabz/multi-service-worker ./worker

  # login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # take images and push to docker hub
  - docker push khemgabz/multi-service-client
  - docker push khemgabz/multi-service-nginx
  - docker push khemgabz/multi-service-server
  - docker push khemgabz/multi-service-worker
# set-up AWS
# deploy:
#   provider: elasticbeanstalk
#   region: south-east-asia1
#   app: multi-service
#   env: Multidocker-env
#   bucket_name: elasticbeanstalk-south-east-asia-s3_id
#   bucket_path: docker-multi
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: $AWS_SECRET_KEY
